AllCops:
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/ClassVars:
  Enabled: false

Metrics/ModuleLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 28
